version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u181-jdk-node-browsers
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install NPM Dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Build Project
          command: npm run build

      - run:
          name: Start Selenium Server
          command: npm run pretest
          background: true

      - run:
          name: Check Selenium Server
          shell: /bin/sh
          command: |
            wget --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 10 http://localhost:4444
            :

      - run:
          name: Run E2E Test
          command: npm run startTest

